[tool.mypy]
strict = true
python_version = "3.10"
explicit_package_bases = true
disallow_any_unimported = true
disallow_any_decorated = true
disallow_any_explicit = true
no_implicit_optional = true
warn_unreachable = true
ignore_missing_imports = false
warn_no_return = true
local_partial_types = true
show_error_codes = true
show_column_numbers = true
show_error_end = true
pretty = true
show_error_context = true
incremental = true

[[tool.mypy.overrides]]
module = [
    "plotly",
    "plotly.express",
    "plotly_calplot"
]
ignore_missing_imports = true

[tool.ruff]
line-length = 175 # The formatter wraps lines at a length of 256
extend-include = ["*.ipynb"] # Allow linting jupyter notebooks.

[tool.ruff.lint]
select = ["ALL"] # It will be clear after some time what rules we do not want, so for now let's use all of them
ignore = [
    "D203",   # Disable "1 blank line required before class docstring" as it is not compatible with D211
    "D213",   # Disable "Multi-line docstring summary should start at the second line" as it is not compatible with D212
    "COM812", # The following rules may cause conflicts when used with the formatter: `COM812`, `ISC001`.
    "ISC001", # The following rules may cause conflicts when used with the formatter: `COM812`, `ISC001`.
    "T201",   # Disable as "prints may be used by some people".
    "TRY400", # Disable as we use structlog
    "TRY401",  # Disable as we use structlog
    "PLR2004" # Magic value used in comparison
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.pycodestyle]
max-line-length = 175 # E501 reports lines that exceed the length of 256
