name: CI and Deployment

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v4
      - name: Use Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run Ruff
        run: pipenv run ruff check ./src
      - name: Run Mypy
        run: pipenv run mypy ./src
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Deploy documentation
        run: pipenv run mkdocs gh-deploy --force
